window.REGION = {
  id: 'ballantyne',
  name: 'Ballantyne',
  sub: '· DISCOVERY MAP · MECKLENBURG COUNTY · NORTH CAROLINA · 2026 EDITION ·',
  credit: '© Ballantyne Discovery Map · 2026 · ballantyneDiscovery.com',
  interactiveCredit: 'Click any marker · Pan &amp; zoom to explore · ballantyneDiscovery.com',
  center: [35.054, -80.849],
  zoom: 14,
  printZoom: 13,

  palette: {
    '--ink':          '#1A2838',
    '--frame':        '#1E3C64',
    '--parch':        '#EEF4F8',
    '--parch-dark':   '#C8DCF0',
    '--accent':       '#C04830',
    '--navy':         '#1E3C64',
    '--green':        '#2A6848',
    '--inner-border': '#9AB8D8',
    '--tile-filter':  'hue-rotate(195deg) saturate(0.7) brightness(1.08) contrast(0.93)',
    '--tile-blend':   'multiply',
    '--tile-opa':     '0.85',
  },

  cats: {
    outdoor: '#2A6848',
    food:    '#C04830',
    coffee:  '#4A2A60',
    arts:    '#1E3C64',
    family:  '#0A5848',
  },

  legend: [
    { color: '#2A6848', label: 'Outdoors' },
    { color: '#C04830', label: 'Eat &amp; Drink' },
    { color: '#4A2A60', label: 'Coffee' },
    { color: '#1E3C64', label: 'Arts &amp; Wellness' },
    { color: '#0A5848', label: 'Family Fun' },
  ],

  places: [
    /* Ballantyne Village core */
    { lat:35.0528, lon:-80.8453, n:1,  cat:'food',
      name:'Ballantyne Village',
      short:'Open-air shops · restaurants · cinema',
      desc:'Heart of Ballantyne — open-air shops, restaurants, boutiques, and a cinema all in one walkable block.',
      meta:'15253 Ballantyne Village Way · Daily 10–9' },
    { lat:35.0540, lon:-80.8438, n:2,  cat:'family',
      name:'Regal Ballantyne',
      short:'5-screen cinema · stadium seating',
      desc:'Five-screen neighborhood cinema with stadium seating. Great for date nights and rainy afternoons.',
      meta:'Ballantyne Village · regalcinemas.com' },
    { lat:35.0532, lon:-80.8442, n:3,  cat:'coffee',
      name:'Summit Coffee',
      short:'Davidson-rooted specialty roasts',
      desc:'Davidson-rooted specialty coffee — locally sourced beans, excellent pour-overs, and a welcoming crowd.',
      meta:'· Ballantyne Village · Mon–Sat 7–6' },
    { lat:35.0524, lon:-80.8462, n:4,  cat:'food',
      name:'Brixx Wood Fired Pizza',
      short:'Thin-crust pies · craft beer',
      desc:'Thin-crust wood-fired pies, fresh salads, and a solid craft beer selection.',
      meta:'· Ballantyne Village · brixxpizza.com' },
    { lat:35.0521, lon:-80.8456, n:5,  cat:'food',
      name:'Baku',
      short:'Pan-Asian fusion · sushi · ramen',
      desc:'Pan-Asian fusion: sushi, ramen, Thai curries. A beloved Ballantyne dinner spot.',
      meta:'· Ballantyne Village' },
    { lat:35.0530, lon:-80.8468, n:6,  cat:'coffee',
      name:'Not Just Coffee',
      short:'Expert espresso · cozy seating',
      desc:'Charlotte-grown café with expert espresso, cozy seating, and grab-and-go pastries.',
      meta:'· Ballantyne Commons Pkwy' },

    /* Ballantyne Hotel campus */
    { lat:35.0578, lon:-80.8622, n:7,  cat:'arts',
      name:'Kimpton Ballantyne Hotel',
      short:'Forbes Four-Star · golf · spa',
      desc:'Forbes Four-Star luxury hotel with a championship golf course, full-service spa, and exceptional dining.',
      meta:'10000 Ballantyne Commons Pkwy · ballantynehotel.com' },
    { lat:35.0581, lon:-80.8618, n:8,  cat:'food',
      name:"Connors Restaurant",
      short:'Dry-aged steaks · Southern sides',
      desc:"Upscale steakhouse inside the Kimpton. Dry-aged cuts, Southern sides, expertly crafted cocktails.",
      meta:'10000 Ballantyne Commons Pkwy · Dinner nightly' },
    { lat:35.0576, lon:-80.8626, n:9,  cat:'arts',
      name:'The Spa at Ballantyne',
      short:'Forbes-rated · massage · heated pool',
      desc:'Forbes-rated full-service spa — massage, facials, sauna, steam, and a heated outdoor pool.',
      meta:'Kimpton Ballantyne Hotel · theballantynespa.com' },

    /* Parks & outdoors */
    { lat:35.0648, lon:-80.8618, n:10, cat:'outdoor',
      name:'Ballantyne Community Park',
      short:'Trails · sports fields · dog park',
      desc:'Paved trails, sports fields, picnic shelters, a playground, and a beloved off-leash dog park.',
      meta:'14904 Ballantyne Meadows Cir · Dawn–dusk' },
    { lat:35.0660, lon:-80.8718, n:11, cat:'outdoor',
      name:'Piper Glen Golf Club',
      short:'Tom Fazio 18-hole design',
      desc:'Semi-private Tom Fazio 18-hole design carved through wooded hills. Walking-friendly year-round.',
      meta:'12300 Piper Glen Dr · piperglen.com' },
    { lat:35.0558, lon:-80.8493, n:12, cat:'outdoor',
      name:'Ballantyne Greenway',
      short:'Paved multi-use trail · bikes &amp; strollers',
      desc:'Paved multi-use path connecting neighborhoods and parks — ideal for bikes, runs, and strollers.',
      meta:'Access off Ballantyne Commons Pkwy · Dawn–dusk' },

    /* Arts & community */
    { lat:35.0538, lon:-80.8473, n:13, cat:'arts',
      name:'Ballantyne Branch Library',
      short:'Maker space · kids section · events',
      desc:'Bright PLCMC branch with a kids section, maker space, study rooms, and frequent author events.',
      meta:'19102 W. Catawba Ave · Mon–Sat 9–8' },

    /* More food & shopping */
    { lat:35.0488, lon:-80.8318, n:14, cat:'food',
      name:'Stonecrest at Piper Glen',
      short:'Open-air center · Harris Teeter anchor',
      desc:'Walkable open-air center anchored by Harris Teeter — great restaurants, coffee, and quick bites.',
      meta:'7804 Rea Rd · stonecrestshopping.com' },
    { lat:35.0496, lon:-80.8383, n:15, cat:'coffee',
      name:'Starbucks Reserve — Ballantyne',
      short:'Nitro Cold Brew · Oleato · Reserve bar',
      desc:'Spacious Reserve bar — Nitro Cold Brew, rare single-origins, and Oleato drinks.',
      meta:'Rea Rd &amp; Ardrey Kell · Daily 5am–9pm' },
  ],

  printRails: {
    left: [
      { head: '☕ Coffee &amp; Cafés', cls: 'coffee', nums: [3, 6, 15] },
      { head: '🥾 Get Outside!',       cls: 'do',     nums: [10, 11, 12] },
    ],
    right: [
      { head: '🍽 Eat &amp; Drink',       cls: 'eat', nums: [8, 4, 5] },
      { head: '⭐ Arts &amp; Wellness',   cls: 'fam', nums: [7, 9, 13] },
    ],
  },
};
