window.REGION = {
  id: 'ballantyne',
  name: 'Ballantyne',
  sub: '· MECKLENBURG COUNTY · NORTH CAROLINA · 2026 EDITION ·',
  credit: '© Ballantyne Map · 2026 · ballantyneMap.com',
  interactiveCredit: 'Click any marker · Pan &amp; zoom to explore · ballantyneMap.com',
  center: [35.054, -80.849],
  zoom: 15,
  printZoom: 15,

  palette: {
    '--ink':          '#1A2838',
    '--frame':        '#1E3C64',
    '--parch':        '#EEF4F8',
    '--parch-dark':   '#C8DCF0',
    '--accent':       '#C04830',
    '--navy':         '#1E3C64',
    '--green':        '#2A6848',
    '--inner-border': '#9AB8D8',
    '--tile-filter':  'saturate(1.2) brightness(1.05) contrast(0.92)',
    '--tile-blend':   'normal',
    '--tile-opa':     '1',
  },

  cats: {
    outdoor: '#2A6848',
    food:    '#C04830',
    coffee:  '#4A2A60',
    arts:    '#1E3C64',
    family:  '#0A5848',
  },

  legend: [
    { color: '#2A6848', label: 'Outdoors' },
    { color: '#C04830', label: 'Eat &amp; Drink' },
    { color: '#4A2A60', label: 'Coffee' },
    { color: '#1E3C64', label: 'Arts &amp; Wellness' },
    { color: '#0A5848', label: 'Family Fun' },
  ],

  places: [
    /* Ballantyne Village core */
    { lat:35.0528, lon:-80.8453, n:1,  cat:'food',
      name:'Ballantyne Village',
      short:'Open-air shops · restaurants · cinema',
      desc:'Heart of Ballantyne — open-air shops, restaurants, boutiques, and a cinema all in one walkable block.',
      meta:'15253 Ballantyne Village Way · Mon–Sat 10–9, Sun 12–6',
      img:'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/ca/30/93/ballantyne-village.jpg' },
    { lat:35.0540, lon:-80.8438, n:2,  cat:'family',
      name:'Regal Ballantyne',
      short:'5-screen cinema · stadium seating',
      desc:'Five-screen neighborhood cinema with stadium seating. Great for date nights and rainy afternoons.',
      meta:'Ballantyne Village · Daily 11am–10pm · regalcinemas.com',
      img:'https://photos.cinematreasures.org/production/photos/165326/1461280214/large.jpg' },
    { lat:35.0532, lon:-80.8442, n:3,  cat:'coffee',
      name:'Summit Coffee',
      short:'Davidson-rooted specialty roasts',
      desc:'Davidson-rooted specialty coffee — locally sourced beans, excellent pour-overs, and a welcoming crowd.',
      meta:'Ballantyne Village · Mon–Fri 7am–6pm, Sat 8am–5pm',
      img:'assets/summit-coffee.png' },
    { lat:35.0517, lon:-80.8452, n:4,  cat:'food',
      name:"Postino's Ballantyne",
      short:'Wine · bruschetta boards · The Bowl',
      desc:'Lively Italian-inspired wine bar and café serving bruschetta boards, sandwiches, and an excellent wine list in a vibrant setting.',
      meta:'15210 Bowl St, Ste 103 · The Bowl at Ballantyne · Mon–Thu 11am–11pm, Fri 11am–midnight, Sat 10am–midnight, Sun 10am–10pm',
      img:'assets/postino.jpg' },
    { lat:35.0519, lon:-80.8455, n:5,  cat:'food',
      name:"Rooster's Wood-fired Kitchen",
      short:'Wood-fired · locally sourced · The Bowl',
      desc:'Charlotte favorite serving elevated American cuisine — wood-fired rotisserie chicken, hand-cut steaks, and an excellent wine bar.',
      meta:'15110 Bowl St · The Bowl at Ballantyne · Mon–Thu 11am–10pm, Fri–Sat 11am–11pm, Sun 11am–10pm',
      img:'assets/roosters-ballantyne.jpg' },
    { lat:35.0518, lon:-80.8452, n:6,  cat:'coffee',
      name:'Copain Bakery & Provisions',
      short:'French bakery · pastries · full bar',
      desc:'Ballantyne\'s beloved French boulangerie-pâtisserie — handcrafted croissants, fresh-baked breads, pastries, and a full brasserie bar.',
      meta:'14020 Stream Way · The Bowl at Ballantyne · Daily 7am–10pm',
      img:'assets/copain-logo.svg' },

    /* Ballantyne Hotel campus */
    { lat:35.0578, lon:-80.8622, n:7,  cat:'arts',
      name:'Kimpton Ballantyne Hotel',
      short:'Forbes Four-Star · golf · spa',
      desc:'Forbes Four-Star luxury hotel with a championship golf course, full-service spa, and exceptional dining.',
      meta:'10000 Ballantyne Commons Pkwy · Open 24 hrs · ballantynehotel.com',
      img:'https://d18slle4wlf9ku.cloudfront.net/theballantynehotel.com-1441752546/cms/imagepool/6667414709fd7.jpg' },
    { lat:35.0481, lon:-80.8403, n:8,  cat:'food',
      name:'131 Main',
      short:'Hickory wood-fired steaks · fresh seafood',
      desc:'Upscale-casual New American steakhouse with hickory wood-fire grilled steaks, chops, and dock-fresh seafood — all made from scratch daily.',
      meta:'9886 Rea Rd · Blakeney · Sun–Thu 11am–9pm, Fri–Sat 11am–9:30pm',
      img:'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/89/cf/35/131-main.jpg' },
    { lat:35.0576, lon:-80.8626, n:9,  cat:'arts',
      name:'The Spa at Ballantyne',
      short:'Forbes-rated · massage · heated pool',
      desc:'Forbes-rated full-service spa — massage, facials, sauna, steam, and a heated outdoor pool.',
      meta:'Kimpton Ballantyne Hotel · Daily 9am–7pm · theballantynespa.com',
      img:'https://d18slle4wlf9ku.cloudfront.net/theballantynehotel.com-1441752546/cms/imagepool/668465fc8a14b.jpg' },

    /* Parks & outdoors */
    { lat:35.0648, lon:-80.8618, n:10, cat:'outdoor',
      name:'Ballantyne Community Park',
      short:'Trails · sports fields · dog park',
      desc:'Paved trails, sports fields, picnic shelters, a playground, and a beloved off-leash dog park.',
      meta:'14904 Ballantyne Meadows Cir · Daily dawn–dusk',
      img:'https://northwoodoffice-assets.imgix.net/goBallantyne/images/common/ballantynes-backyard-community-park-4.jpg' },
    { lat:35.0660, lon:-80.8718, n:11, cat:'outdoor',
      name:'Piper Glen Golf Club',
      short:'Tom Fazio 18-hole design',
      desc:'Semi-private Tom Fazio 18-hole design carved through wooded hills. Walking-friendly year-round.',
      meta:'12300 Piper Glen Dr · Daily 7am–dusk · piperglen.com',
      img:'https://golf-pass-brightspot.s3.amazonaws.com/4a/ef/d844c0c723207813d2c6121f0ff3/37559.jpg' },
    { lat:35.0558, lon:-80.8493, n:12, cat:'outdoor',
      name:'Ballantyne Greenway',
      short:'Paved multi-use trail · bikes &amp; strollers',
      desc:'Paved multi-use path connecting neighborhoods and parks — ideal for bikes, runs, and strollers.',
      meta:'Ballantyne Commons Pkwy · Daily dawn–dusk · Free',
      img:'https://files.aptuitivcdn.com/JVXM9wad0E-1708/images/trails/trail-system/IMG_2596_horiz-57.1773311125.jpg' },

    /* Arts & community */
    { lat:35.0538, lon:-80.8473, n:13, cat:'arts',
      name:'Ballantyne Branch Library',
      short:'Maker space · kids section · events',
      desc:'Bright PLCMC branch with a kids section, maker space, study rooms, and frequent author events.',
      meta:'19102 W. Catawba Ave · Mon–Thu 9am–8pm, Fri–Sat 9am–6pm',
      img:'https://digitalbranch.cmlibrary.org/wp-content/uploads/2022/02/south-county-1024x683.jpg' },

    /* More food & shopping */
    { lat:35.0488, lon:-80.8318, n:14, cat:'food',
      name:'Stonecrest at Piper Glen',
      short:'Open-air center · Harris Teeter anchor',
      desc:'Walkable open-air center anchored by Harris Teeter — great restaurants, coffee, and quick bites.',
      meta:'7804 Rea Rd · Mon–Sat 9am–9pm, Sun 10am–7pm',
      img:'https://mpvre.com/wp-content/uploads/2022/07/StoneCrest-fountains-dawn-1920px.jpg' },
    { lat:35.0496, lon:-80.8383, n:15, cat:'coffee',
      name:'Haraz Coffee House',
      short:'Yemeni coffee · tea · cozy vibes',
      desc:'Authentic Yemeni coffee house serving specialty brews, loose-leaf teas, and Middle Eastern pastries in a warm, welcoming space.',
      meta:'15205 John J Delaney Dr, Ste B · Daily 8am–10pm',
      img:'assets/haraz-logo.png', fitContain:true },

    /* Arts & Wellness */
    { lat:35.0535, lon:-80.8444, n:16, cat:'arts',
      name:'Solidcore',
      short:'High-intensity Pilates · reformer classes',
      desc:'High-intensity, low-impact Pilates on reformer machines. Challenging classes for all levels.',
      meta:'Ballantyne · Mon–Fri 5:30am–8pm, Sat–Sun 7am–1pm · solidcore.co',
      img:'https://northwoodoffice-assets.imgix.net/goBallantyne/images/common/432383790-solidcore-batch-1-revised-10-sm.jpg' },
    { lat:35.0535, lon:-80.8453, n:17, cat:'arts',
      name:'The Daily Pilates',
      short:'Reformer pilates · all levels · Ballantyne Village',
      desc:'Boutique reformer Pilates studio right in Ballantyne Village — expert instructors, small classes, and a beautiful airy space.',
      meta:'14835 Ballantyne Village Way · Mon–Thu 6am–8pm, Fri–Sun 6am–1:30pm',
      img:'assets/daily-pilates.jpg' },
    { lat:35.0612, lon:-80.8580, n:18, cat:'arts',
      name:'YogaSix Ballantyne',
      short:'Hot yoga · barre · meditation',
      desc:'Community yoga studio offering hot yoga, barre, and meditation classes for all levels.',
      meta:'Ballantyne Village Way · Mon–Fri 6am–8pm, Sat–Sun 7:30am–1pm',
      img:'https://www.yogasix.com/hubfs/Resized%20Location%20Page%20Images/Rectangle-1010.jpg' },

    /* Family & Fun */
    { lat:35.0522, lon:-80.8448, n:19, cat:'family',
      name:'The Bowl at Ballantyne',
      short:'Dining · entertainment · community hub',
      desc:'Ballantyne\'s vibrant mixed-use district with dining, entertainment, and a welcoming community vibe.',
      meta:'Ballantyne Village Way · Daily 11am–10pm',
      img:'https://northwoodoffice-assets.imgix.net/goBallantyne/images/common/The-Bowl-20-sm.jpeg' },
    { lat:35.0516, lon:-80.8443, n:20, cat:'family',
      name:'Game Show Battle Rooms',
      short:'Live game show experience · groups',
      desc:'Interactive live game show experience — compete in teams across hilarious TV-style challenges.',
      meta:'Ballantyne · Wed–Fri 3–9pm, Sat 11am–10pm, Sun 12–7pm',
      img:'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/32/38/d7/3b/game-show-battle-rooms.jpg?w=700&h=400&s=1' },
    { lat:35.0512, lon:-80.8435, n:21, cat:'family',
      name:'Sports Connection',
      short:'Bowling · laser tag · arcade · skating',
      desc:'Massive family entertainment complex with bowling, laser tag, roller skating, and arcade games.',
      meta:'Ballantyne · Mon–Thu 11am–10pm, Fri–Sat 11am–midnight, Sun 12–9pm',
      img:'https://sportsconnectionnc.com/wp-content/uploads/2022/08/DSC_4955-e1666210372562.jpg' },
    { lat:35.0526, lon:-80.8466, n:22, cat:'family',
      name:'Fly Kid Fly',
      short:'Kids indoor play · climbing · fun',
      desc:'Indoor adventure play space for kids — climbing, jumping, and imaginative play in a safe environment.',
      meta:'Ballantyne · Mon–Fri 9am–6pm, Sat–Sun 9am–7pm',
      img:'assets/fly-kid-fly-logo.svg', fitContain:true, bgColor:'#3B78C9' },

    /* More food */
    { lat:35.0518, lon:-80.8452, n:23, cat:'food',
      name:'Arrow',
      short:'Cuts &amp; shaves · complimentary beer',
      desc:'Ballantyne\'s coolest barber shop — sharp cuts, straight-razor shaves, and a complimentary cold beer.',
      meta:'The Bowl at Ballantyne · Tue–Sat 9am–7pm, Sun 10am–4pm',
      img:'https://northwoodoffice-assets.imgix.net/northwood/images/news/IMG_7973-2.jpeg' },
    { lat:35.0517, lon:-80.8454, n:27, cat:'food',
      name:"Bossy Beulah's",
      short:'Hot chicken · crispy tenders · The Bowl',
      desc:'Carolina-born hot chicken joint serving legendary crispy tenders, sandwiches, and sauces with serious heat.',
      meta:'15110 Bowl St, Ste 103 · The Bowl at Ballantyne · Daily 11am–9pm',
      img:'assets/bossy-beulahs.jpg' },
    { lat:35.0496, lon:-80.8399, n:26, cat:'coffee',
      name:'Littl Madeleine',
      short:'Organic coffee · French bakery · pastries',
      desc:'Charming organic coffee and bakery café — handcrafted madeleines, seasonal pastries, and specialty coffee in a cozy Ballantyne spot.',
      meta:'11318 N Community House Rd #202 · Mon–Sat 8am–5pm',
      img:'assets/littl-madeleine.svg', fitContain:true, bgColor:'#B8DADA' },
    { lat:35.0531, lon:-80.8457, n:24, cat:'coffee',
      name:'Salty Donut',
      short:'Artisan donuts · small-batch coffee',
      desc:'Miami-born artisan donut shop with inventive flavors, small-batch coffee, and a serious cult following.',
      meta:'Ballantyne · Mon–Fri 7am–2pm, Sat–Sun 7am–3pm · saltydonut.com',
      img:'https://northwoodoffice-assets.imgix.net/goBallantyne/images/common/sal_41-sm.jpg' },
    { lat:35.0519, lon:-80.8461, n:25, cat:'food',
      name:'Flower Child',
      short:'Healthy bowls · wraps · feel-good food',
      desc:'Feel-good restaurant focused on clean, nourishing food — bowls, wraps, salads, and fresh juices.',
      meta:'Ballantyne · Mon–Sun 11am–9pm · iamaflowerchild.com',
      img:'https://images.axios.com/okQlcUmYthPGHDJeeW2b-AOzrmE=/0x426:4032x2694/1920x1080/2024/05/16/1715869904527.jpg' },
  ],

  printRails: {
    top: [
      { head: '⭐ Arts &amp; Wellness', cls: 'fam', nums: [7, 9, 23, 16, 17, 18], lightText: true },
    ],
    left: [
      { head: '☕ Coffee &amp; Cafés', cls: 'coffee', nums: [3, 15, 22, 6, 26] },
    ],
    right: [
      { head: '🍽 Eat &amp; Drink', cls: 'eat', nums: [8, 4, 5, 27, 25] },
    ],
    mapBelow: [
      { head: '🥾 Get Outside!', cls: 'do', nums: [10, 11, 12] },
    ],
    bottom: [
      { head: '🎳 Family &amp; Fun', cls: 'fam', nums: [2, 19, 20, 21] },
    ],
  },
};
