window.REGION = {
  id: 'ballantyne',
  name: 'Ballantyne',
  sub: '· MECKLENBURG COUNTY · NORTH CAROLINA · 2026 EDITION ·',
  credit: '© Ballantyne Map · 2026 · ballantyneMap.com',
  interactiveCredit: 'Click any marker · Pan &amp; zoom to explore · ballantyneMap.com',
  center: [35.054, -80.849],
  zoom: 15,
  printZoom: 15,

  palette: {
    '--ink':          '#1A2838',
    '--frame':        '#1E3C64',
    '--parch':        '#EEF4F8',
    '--parch-dark':   '#C8DCF0',
    '--accent':       '#C04830',
    '--navy':         '#1E3C64',
    '--green':        '#2A6848',
    '--inner-border': '#9AB8D8',
    '--tile-filter':  'saturate(1.2) brightness(1.05) contrast(0.92)',
    '--tile-blend':   'normal',
    '--tile-opa':     '1',
  },

  cats: {
    outdoor: '#2A6848',
    food:    '#C04830',
    coffee:  '#4A2A60',
    arts:    '#1E3C64',
    family:  '#0A5848',
  },

  legend: [
    { color: '#2A6848', label: 'Outdoors' },
    { color: '#C04830', label: 'Eat &amp; Drink' },
    { color: '#4A2A60', label: 'Coffee' },
    { color: '#1E3C64', label: 'Arts &amp; Wellness' },
    { color: '#0A5848', label: 'Family Fun' },
  ],

  places: [
    /* Ballantyne Village core */
    { lat:35.0528, lon:-80.8453, n:1,  cat:'food',
      name:'Ballantyne Village',
      short:'Open-air shops · restaurants · cinema',
      desc:'Heart of Ballantyne — open-air shops, restaurants, boutiques, and a cinema all in one walkable block.',
      meta:'15253 Ballantyne Village Way · Daily 10–9',
      img:'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/ca/30/93/ballantyne-village.jpg' },
    { lat:35.0540, lon:-80.8438, n:2,  cat:'family',
      name:'Regal Ballantyne',
      short:'5-screen cinema · stadium seating',
      desc:'Five-screen neighborhood cinema with stadium seating. Great for date nights and rainy afternoons.',
      meta:'Ballantyne Village · regalcinemas.com',
      img:'https://photos.cinematreasures.org/production/photos/165326/1461280214/large.jpg' },
    { lat:35.0532, lon:-80.8442, n:3,  cat:'coffee',
      name:'Summit Coffee',
      short:'Davidson-rooted specialty roasts',
      desc:'Davidson-rooted specialty coffee — locally sourced beans, excellent pour-overs, and a welcoming crowd.',
      meta:'· Ballantyne Village · Mon–Sat 7–6', img:'assets/summit-coffee.png' },
    { lat:35.0524, lon:-80.8462, n:4,  cat:'food',
      name:'Brixx Wood Fired Pizza',
      short:'Thin-crust pies · craft beer',
      desc:'Thin-crust wood-fired pies, fresh salads, and a solid craft beer selection.',
      meta:'· Ballantyne Village · brixxpizza.com' },
    { lat:35.0521, lon:-80.8456, n:5,  cat:'food',
      name:'Baku',
      short:'Pan-Asian fusion · sushi · ramen',
      desc:'Pan-Asian fusion: sushi, ramen, Thai curries. A beloved Ballantyne dinner spot.',
      meta:'· Ballantyne Village',
      img:'https://media-cdn.tripadvisor.com/media/photo-s/19/41/57/3f/baku.jpg' },
    { lat:35.0530, lon:-80.8468, n:6,  cat:'coffee',
      name:'Not Just Coffee',
      short:'Expert espresso · cozy seating',
      desc:'Charlotte-grown café with expert espresso, cozy seating, and grab-and-go pastries.',
      meta:'· Ballantyne Commons Pkwy',
      img:'https://images.squarespace-cdn.com/content/v1/54592b9ae4b0d95c60e0fac6/b95352a4-a8c7-46ce-be17-f002d3ea868c/image_6483441+%281%29.jpg' },

    /* Ballantyne Hotel campus */
    { lat:35.0578, lon:-80.8622, n:7,  cat:'arts',
      name:'Kimpton Ballantyne Hotel',
      short:'Forbes Four-Star · golf · spa',
      desc:'Forbes Four-Star luxury hotel with a championship golf course, full-service spa, and exceptional dining.',
      meta:'10000 Ballantyne Commons Pkwy · ballantynehotel.com',
      img:'https://d18slle4wlf9ku.cloudfront.net/theballantynehotel.com-1441752546/cms/imagepool/6667414709fd7.jpg' },
    { lat:35.0581, lon:-80.8618, n:8,  cat:'food',
      name:"Connors Restaurant",
      short:'Dry-aged steaks · Southern sides',
      desc:"Upscale steakhouse inside the Kimpton. Dry-aged cuts, Southern sides, expertly crafted cocktails.",
      meta:'10000 Ballantyne Commons Pkwy · Dinner nightly',
      img:'https://d18slle4wlf9ku.cloudfront.net/theballantynehotel.com-1441752546/cms/imagepool/6671f8f23982e.jpg' },
    { lat:35.0576, lon:-80.8626, n:9,  cat:'arts',
      name:'The Spa at Ballantyne',
      short:'Forbes-rated · massage · heated pool',
      desc:'Forbes-rated full-service spa — massage, facials, sauna, steam, and a heated outdoor pool.',
      meta:'Kimpton Ballantyne Hotel · theballantynespa.com',
      img:'https://d18slle4wlf9ku.cloudfront.net/theballantynehotel.com-1441752546/cms/imagepool/668465fc8a14b.jpg' },

    /* Parks & outdoors */
    { lat:35.0648, lon:-80.8618, n:10, cat:'outdoor',
      name:'Ballantyne Community Park',
      short:'Trails · sports fields · dog park',
      desc:'Paved trails, sports fields, picnic shelters, a playground, and a beloved off-leash dog park.',
      meta:'14904 Ballantyne Meadows Cir · Dawn–dusk',
      img:'https://northwoodoffice-assets.imgix.net/goBallantyne/images/common/ballantynes-backyard-community-park-4.jpg' },
    { lat:35.0660, lon:-80.8718, n:11, cat:'outdoor',
      name:'Piper Glen Golf Club',
      short:'Tom Fazio 18-hole design',
      desc:'Semi-private Tom Fazio 18-hole design carved through wooded hills. Walking-friendly year-round.',
      meta:'12300 Piper Glen Dr · piperglen.com',
      img:'https://golf-pass-brightspot.s3.amazonaws.com/4a/ef/d844c0c723207813d2c6121f0ff3/37559.jpg' },
    { lat:35.0558, lon:-80.8493, n:12, cat:'outdoor',
      name:'Ballantyne Greenway',
      short:'Paved multi-use trail · bikes &amp; strollers',
      desc:'Paved multi-use path connecting neighborhoods and parks — ideal for bikes, runs, and strollers.',
      meta:'Access off Ballantyne Commons Pkwy · Dawn–dusk',
      img:'https://files.aptuitivcdn.com/JVXM9wad0E-1708/images/trails/trail-system/IMG_2596_horiz-57.1773311125.jpg' },

    /* Arts & community */
    { lat:35.0538, lon:-80.8473, n:13, cat:'arts',
      name:'Ballantyne Branch Library',
      short:'Maker space · kids section · events',
      desc:'Bright PLCMC branch with a kids section, maker space, study rooms, and frequent author events.',
      meta:'19102 W. Catawba Ave · Mon–Sat 9–8',
      img:'https://digitalbranch.cmlibrary.org/wp-content/uploads/2022/02/south-county-1024x683.jpg' },

    /* More food & shopping */
    { lat:35.0488, lon:-80.8318, n:14, cat:'food',
      name:'Stonecrest at Piper Glen',
      short:'Open-air center · Harris Teeter anchor',
      desc:'Walkable open-air center anchored by Harris Teeter — great restaurants, coffee, and quick bites.',
      meta:'7804 Rea Rd · stonecrestshopping.com',
      img:'https://mpvre.com/wp-content/uploads/2022/07/StoneCrest-fountains-dawn-1920px.jpg' },
    { lat:35.0496, lon:-80.8383, n:15, cat:'coffee',
      name:'Starbucks Reserve — Ballantyne',
      short:'Nitro Cold Brew · Oleato · Reserve bar',
      desc:'Spacious Reserve bar — Nitro Cold Brew, rare single-origins, and Oleato drinks.',
      meta:'Rea Rd &amp; Ardrey Kell · Daily 5am–9pm',
      img:'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/2c/1d/d9/inside.jpg' },

    /* Arts & Wellness */
    { lat:35.0535, lon:-80.8444, n:16, cat:'arts',
      name:'Solidcore',
      short:'High-intensity Pilates · reformer classes',
      desc:'High-intensity, low-impact Pilates on reformer machines. Challenging classes for all levels.',
      meta:'· Ballantyne · solidcore.co',
      img:'https://northwoodoffice-assets.imgix.net/goBallantyne/images/common/432383790-solidcore-batch-1-revised-10-sm.jpg' },
    { lat:35.0544, lon:-80.8470, n:17, cat:'arts',
      name:'Superior Real Estate School',
      short:'Real estate licensing · CE courses',
      desc:'Top-rated real estate licensing and continuing education school serving the greater Charlotte area.',
      meta:'· Ballantyne · superiorrealestateschool.com',
      img:'https://www.superiorschoolnc.com/wp-content/uploads/2025/11/Superior-Home-Hero-21-1024x731-1.png' },
    { lat:35.0612, lon:-80.8580, n:18, cat:'arts',
      name:'YogaSix Ballantyne',
      short:'Hot yoga · barre · meditation',
      desc:'Community yoga studio offering hot yoga, barre, and meditation classes for all levels.',
      meta:'· Ballantyne Village Way · yogasix.com',
      img:'https://www.yogasix.com/hubfs/Resized%20Location%20Page%20Images/Rectangle-1010.jpg' },

    /* Family & Fun */
    { lat:35.0522, lon:-80.8448, n:19, cat:'family',
      name:'The Bowl at Ballantyne',
      short:'Dining · entertainment · community hub',
      desc:'Ballantyne\'s vibrant mixed-use district with dining, entertainment, and a welcoming community vibe.',
      meta:'· Ballantyne Village Way',
      img:'https://northwoodoffice-assets.imgix.net/goBallantyne/images/common/The-Bowl-20-sm.jpeg' },
    { lat:35.0516, lon:-80.8443, n:20, cat:'family',
      name:'Game Show Battle Rooms',
      short:'Live game show experience · groups',
      desc:'Interactive live game show experience — compete in teams across hilarious TV-style challenges.',
      meta:'· Ballantyne · gameshowbattlerooms.com',
      img:'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/32/38/d7/3b/game-show-battle-rooms.jpg?w=700&h=400&s=1' },
    { lat:35.0512, lon:-80.8435, n:21, cat:'family',
      name:'Sports Connection',
      short:'Bowling · laser tag · arcade · skating',
      desc:'Massive family entertainment complex with bowling, laser tag, roller skating, and arcade games.',
      meta:'· Ballantyne · sportsconnection.com',
      img:'https://sportsconnectionnc.com/wp-content/uploads/2022/08/DSC_4955-e1666210372562.jpg' },
    { lat:35.0526, lon:-80.8466, n:22, cat:'family',
      name:'Fly Kid Fly',
      short:'Kids indoor play · climbing · fun',
      desc:'Indoor adventure play space for kids — climbing, jumping, and imaginative play in a safe environment.',
      meta:'· Ballantyne area',
      img:'https://cdn.prod.website-files.com/67f03b0f48a5186df3a00afe/685d8daff75155fa8d8949bf_FlyKid_240601.jpg' },

    /* More food */
    { lat:35.0518, lon:-80.8452, n:23, cat:'food',
      name:'Arrow',
      short:'Cuts &amp; shaves · complimentary beer',
      desc:'Ballantyne\'s coolest barber shop — sharp cuts, straight-razor shaves, and a complimentary cold beer.',
      meta:'· The Bowl at Ballantyne',
      img:'https://northwoodoffice-assets.imgix.net/northwood/images/news/IMG_7973-2.jpeg' },
    { lat:35.0502, lon:-80.8350, n:26, cat:'coffee',
      name:'Tous Les Jours',
      short:'Korean-French bakery · pastries · coffee',
      desc:'Korean-French bakery café serving beautifully crafted pastries, soft cakes, and quality coffee drinks.',
      meta:'· Ballantyne area · tljus.com',
      img:'https://images.squarespace-cdn.com/content/v1/5b9b5c8596e76f6a7afdcb97/1631567342943-ZQZQZQZQZQZQ/tous-les-jours.jpg' },
    { lat:35.0531, lon:-80.8457, n:24, cat:'coffee',
      name:'Salty Donut',
      short:'Artisan donuts · small-batch coffee',
      desc:'Miami-born artisan donut shop with inventive flavors, small-batch coffee, and a serious cult following.',
      meta:'· Ballantyne · saltydonut.com',
      img:'https://northwoodoffice-assets.imgix.net/goBallantyne/images/common/sal_41-sm.jpg' },
    { lat:35.0519, lon:-80.8461, n:25, cat:'food',
      name:'Flower Child',
      short:'Healthy bowls · wraps · feel-good food',
      desc:'Feel-good restaurant focused on clean, nourishing food — bowls, wraps, salads, and fresh juices.',
      meta:'· Ballantyne · iamaflowerchild.com',
      img:'https://images.axios.com/okQlcUmYthPGHDJeeW2b-AOzrmE=/0x426:4032x2694/1920x1080/2024/05/16/1715869904527.jpg' },
  ],

  printRails: {
    top: [
      { head: '⭐ Arts &amp; Wellness', cls: 'fam', nums: [7, 9, 13, 16, 17, 18] },
    ],
    left: [
      { head: '☕ Coffee &amp; Cafés', cls: 'coffee', nums: [3, 6, 15, 24, 26] },
    ],
    right: [
      { head: '🍽 Eat &amp; Drink', cls: 'eat', nums: [8, 4, 5, 23, 25] },
    ],
    mapBelow: [
      { head: '🥾 Get Outside!', cls: 'do', nums: [10, 11, 12] },
    ],
    bottom: [
      { head: '🎳 Family &amp; Fun', cls: 'fam', nums: [2, 19, 20, 21, 22] },
    ],
  },
};
