window.REGION = {
  id: 'matthews',
  name: 'Matthews',
  sub: '· MECKLENBURG COUNTY · NORTH CAROLINA · 2026 EDITION ·',
  credit: '© LeisurelyMaps · 2026 · leisurelymaps.com',
  interactiveCredit: 'Click any marker · Pan &amp; zoom to explore · leisurelymaps.com',
  center: [35.1193, -80.7201],
  zoom: 14,
  printZoom: 14.5,
  tileUrl: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}',
  tileAttrib: 'Tiles © Esri — Esri, DeLorme, NAVTEQ, TomTom, Intermap, iPC, USGS, FAO, NPS, NRCAN, GeoBase, Kadaster NL, Ordnance Survey, Esri Japan, METI, Esri China (Hong Kong)',

  palette: {
    '--ink':          '#0A1E24',
    '--frame':        '#1A5C6B',
    '--parch':        '#F2F8F9',
    '--parch-dark':   '#D4ECF0',
    '--accent':       '#D4943A',
    '--navy':         '#1A5C6B',
    '--inner-border': '#8ABFC8',
    '--tile-filter':  'saturate(1.0) brightness(1.05) contrast(0.92)',
    '--tile-blend':   'normal',
    '--tile-opa':     '1',
  },

  cats: {
    outdoor: '#1A5C6B',
    food:    '#C04830',
    coffee:  '#8A5A1A',
    arts:    '#1A4A7A',
    family:  '#7A3A8A',
    kids:    '#2A8A5A',
  },

  legend: [
    { color: '#1A5C6B', label: 'Outdoors' },
    { color: '#C04830', label: 'Eat &amp; Drink' },
    { color: '#8A5A1A', label: 'Coffee &amp; Brew' },
    { color: '#1A4A7A', label: 'Arts &amp; Community' },
    { color: '#7A3A8A', label: 'Family &amp; Wellness' },
    { color: '#2A8A5A', label: 'Kids &amp; Family' },
  ],

  places: [

    /* ── BREW & BAR ── */
    { lat:35.1215, lon:-80.7208, n:1, cat:'coffee',
      name:'Matthews Social House',
      short:'Irish pub · craft beer · live music · beer garden',
      desc:'A neighborhood whiskey pub with an Irish soul — perfectly poured Guinness, a lively beer garden, live music, and rotating food trucks make this downtown Matthews\' go-to local hangout.',
      meta:'105 W Charles St · Downtown Matthews · Mon–Thu 3pm–12am, Fri 12pm–2am, Sat 11am–2am, Sun 11am–12am · matthewssocialhouse.com',
      img:'https://static.spotapps.co/website_images/ab_websites/162723_website/events_pbg.jpg',
      price:'$$', tags:['livemusic','outdoor','local'] },

    { lat:35.1210, lon:-80.7198, n:2, cat:'coffee',
      name:'Carolina Beer Temple',
      short:'28 rotating taps · rare craft beer · bottle shop',
      desc:'An independent-only craft beer bar and bottle shop with 28 rotating taps featuring rare finds from the Carolinas and around the world.',
      meta:'215 N Ames St · Ames Station · Mon–Wed 2–10pm, Thu–Sat 12–11pm, Sun 12–8pm · carolinabeertemple.com',
      img:'https://images.squarespace-cdn.com/content/v1/6041a53adf805e76f59d8e4b/1616269448841-JXWEB3ZX6FSJFBE583LV/taps2.jpg',
      price:'$$', tags:['local'] },

    { lat:35.1195, lon:-80.7185, n:3, cat:'coffee',
      name:'Cellar &amp; Ale',
      short:'Wine bar · craft beer · book nook · community events',
      desc:'A cozy, community-minded wine bar and craft beer spot with a book nook, monthly wine tastings, weekly events, and local goods on the shelves.',
      meta:'131 Matthews Station St · Matthews · Tue–Wed 2–9pm, Thu 12–9pm, Fri–Sat 12–10pm, Sun 1–8pm · cellarandale.com',
      img:'https://static.wixstatic.com/media/3cd3fe_485863dc021d4488a72146b8f3437fe0~mv2.jpg',
      price:'$$', tags:['date','local'] },

    /* ── EAT & DRINK ── */
    { lat:35.1200, lon:-80.7215, n:4, cat:'food',
      name:'Santé Fine Dining',
      short:'French-American fine dining · downtown landmark',
      desc:'Elegant French-American fine dining in the heart of historic downtown Matthews, celebrated as the area\'s premier destination restaurant.',
      meta:'165 N Trade St · Downtown Matthews · Tue–Thu 5–9pm, Fri–Sat 5–10pm · santeofmatthews.com',
      img:'https://static.wixstatic.com/media/9aaea0_2bd4599ac3e9409b8924e38749430114~mv2.jpeg',
      price:'$$$', tags:['date','local'] },

    { lat:35.1188, lon:-80.7205, n:5, cat:'food',
      name:'Mac\'s Speed Shop',
      short:'Award-winning BBQ · craft beer · biker-bar vibes',
      desc:'Award-winning BBQ and craft beer joint with slow-smoked brisket, pulled pork, and an unbeatable atmosphere in the heart of downtown Matthews.',
      meta:'142 E John St · Downtown Matthews · Sun–Wed 11am–10pm, Thu–Sat 11am–11pm · macspeedshop.com',
      img:'https://media-cdn.tripadvisor.com/media/photo-f/11/f6/1c/39/nice-and-clean.jpg',
      price:'$$', tags:['outdoor','local'] },

    { lat:35.1098, lon:-80.7195, n:6, cat:'food',
      name:'Stacks Kitchen',
      short:'Breakfast & brunch · generous portions · local favorite',
      desc:'A beloved Matthews breakfast-and-brunch institution known for generous portions, fluffy pancakes, and a warm neighborhood welcome.',
      meta:'11100 Monroe Rd · Matthews · Daily 6am–3pm · stackskitchen.com',
      img:'https://res.cloudinary.com/spothopper/image/fetch/f_auto,q_auto:best,c_fit,h_1200/http://static.spotapps.co/spots/61/ebb3a5cf4146da9335efdc2b358323/:original',
      price:'$', tags:['brunch','family','local'] },

    { lat:35.1192, lon:-80.7180, n:7, cat:'food',
      name:'Thai Taste Matthews',
      short:'Authentic Thai · Pad Thai · curries · local gem',
      desc:'Authentic Thai flavors served in a relaxed setting, from classic Pad Thai to punchy green curries that keep regulars coming back.',
      meta:'131 Matthews Station St · Matthews · Mon–Fri 11am–3pm & 5–9pm, Sat 11am–9:30pm · thaistaste.com',
      img:'https://img02.restaurantguru.com/c333-Thai-Taste-Charlotte-interior.jpg',
      price:'$$', tags:['local'] },

    { lat:35.1175, lon:-80.7220, n:8, cat:'food',
      name:'Lam\'s Kitchen',
      short:'Vietnamese · neighborhood gem · loyal locals',
      desc:'A quiet neighborhood gem serving authentic Vietnamese dishes — the kind of under-the-radar spot that loyal locals keep to themselves.',
      meta:'3016 Weddington Rd · Matthews · Mon & Wed–Fri 11:30am–2:30pm & 4:30–9:30pm · lamskitchen.com',
      img:'https://media-cdn.tripadvisor.com/media/photo-s/16/4e/7d/c6/lam-s-kitchen.jpg',
      price:'$$', tags:['local'] },

    { lat:35.1172, lon:-80.7218, n:24, cat:'food',
      name:'The One Tapas &amp; Bar',
      short:'Global small plates · bold cocktails · date-night gem',
      desc:'The only tapas bar in Matthews — globally inspired small plates from charred octopus to wagyu sliders, paired with creative cocktails in a warm, intimate setting.',
      meta:'3116 Weddington Rd · Matthews · Tue–Thu 4:30–10pm, Fri 4:30–10:30pm, Sat 1–10:30pm, Sun 11:30am–8pm · theonetapas.com',
      img:'https://static.spotapps.co/spots/95/85a3ef8a264a1dbe6aa2986136884b/:original',
      price:'$$$', tags:['date','local'] },

    /* ── COFFEE ── */
    { lat:35.1100, lon:-80.7185, n:9, cat:'coffee',
      name:'Platform Coffee',
      short:'In-house roasted · espresso · pour-overs · 4.9 stars',
      desc:'A beloved neighborhood roaster with a 4.9-star reputation, roasting all beans in-house and serving meticulously crafted espresso and pour-overs.',
      meta:'11011 Monroe Rd · Matthews · Mon–Sat 7am–5pm · platformcoffee.com',
      img:'https://platformcoffee.com/cdn/shop/files/CoffeeAtStationWest_CheyenneSchultzPhotography0122.jpg?v=1717438386&width=1500',
      price:'$', tags:['local','scenic'] },

    { lat:35.1225, lon:-80.7212, n:10, cat:'coffee',
      name:'Brakeman\'s Coffee',
      short:'Downtown staple · espresso · railroad history',
      desc:'A beloved downtown Matthews coffee shop named after the town\'s railroad history, serving quality espresso and supply goods on charming Trade Street.',
      meta:'225 N Trade St · Downtown Matthews · Mon–Fri 6am–7pm, Sat 7am–7pm · brakemanscoffee.com',
      img:'https://media-cdn.tripadvisor.com/media/photo-s/17/30/96/7b/come-see-us-and-find.jpg',
      price:'$', tags:['local'] },

    { lat:35.1155, lon:-80.7050, n:11, cat:'coffee',
      name:'The Collective Cafe',
      short:'Locally roasted coffee · fresh food · community hub',
      desc:'A relaxed neighborhood cafe serving locally roasted coffee and fresh, wholesome food in a space that doubles as a community gathering spot.',
      meta:'1031 Matthews-Mint Hill Rd · Matthews · Mon–Sat 7am–4:30pm · collective-cafe.com',
      img:'https://static.wixstatic.com/media/17ea1a_9fdf48a7e8544d328cc8b2f56814755a~mv2.jpg',
      price:'$', tags:['local'] },

    /* ── OUTDOORS ── */
    { lat:35.1108, lon:-80.7118, n:12, cat:'outdoor',
      name:'Squirrel Lake Park',
      short:'Fishing pier · disc golf · greenway access · 36 acres',
      desc:'A 36-acre park with a fishing pier on a serene pond, 12-hole disc golf, playgrounds, and direct trail access to the Four Mile Creek Greenway.',
      meta:'1631 Pleasant Plains Rd · Matthews · Dawn to dusk · matthewsnc.gov',
      img:'https://cdn.prod.website-files.com/65696e115a35f03f3de93b22/66a9ef2583ed9a58e5a1c8ef_66694b6a6277ae1c45703aa5_Squirrel%252520Lake%252520Park.webp',
      tags:['family','kids','dogs','scenic'] },

    { lat:35.1185, lon:-80.7175, n:13, cat:'outdoor',
      name:'Four Mile Creek Greenway',
      short:'2.3-mile paved trail · boardwalks · pine forest',
      desc:'A beloved 2.3-mile paved greenway winding through mixed pine forest and wetlands with boardwalk sections, connecting downtown to Squirrel Lake Park.',
      meta:'Trailhead at 1102 E John St · Matthews · Dawn to dusk · matthewsnc.gov',
      img:'https://files.aptuitivcdn.com/JVXM9wad0E-1708/images/trails/trail-system/four-mile-creek-greenway-2016-23-large-2-large-2-57.1773311125.jpg',
      tags:['family','dogs','scenic'] },

    { lat:35.1035, lon:-80.7088, n:14, cat:'outdoor',
      name:'Colonel Francis Beatty Park',
      short:'265 acres · mountain biking · kayak rentals · lake',
      desc:'A sprawling 265-acre park with mountain biking and hiking trails, a lake with kayak and canoe rentals, tennis courts, and picnic areas.',
      meta:'4330 Weddington Rd · Matthews · Dawn to dusk · charmeck.org',
      img:'https://kiddingaroundcharlotte.com/wp-content/uploads/sites/3/2026/02/Beatty-Park-4.jpg',
      tags:['family','kids','dogs','scenic'] },

    /* ── ARTS & COMMUNITY ── */
    { lat:35.1178, lon:-80.7198, n:15, cat:'arts',
      name:'Matthews Playhouse',
      short:'Community theater · productions · classes · camps',
      desc:'A beloved nonprofit community theater offering mainstage productions for all ages, year-round drama classes, and summer camps for kids and teens.',
      meta:'100 E McDowell St · Matthews · Box office Mon–Fri 9am–5pm · matthewsplayhouse.com',
      img:'https://static.wixstatic.com/media/99dd65_f00847adebcb46928bf57faff1b2e619~mv2.jpg',
      tags:['kids','family'] },

    { lat:35.1228, lon:-80.7205, n:16, cat:'arts',
      name:'Matthews Heritage Museum',
      short:'Free admission · 1879 historic home · railroad history',
      desc:'Housed in the 1879 Massey-Clark House, this free local history museum preserves the story of the town\'s railroad past in a National Register building.',
      meta:'232 N Trade St · Downtown Matthews · Thu–Sat 10am–4:30pm · Free · matthewsheritagemuseum.org',
      img:'https://matthewsheritagemuseum.org/wp-content/uploads/2021/03/mhm-side-view.jpg?w=1024' },

    { lat:35.1222, lon:-80.7210, n:17, cat:'arts',
      name:'Matthews Farmers\' Market',
      short:'Producer-only · 50-mile radius · largest in area',
      desc:'The Charlotte area\'s largest, oldest, and most diverse producer-only farmers market, with all goods grown or made within 50 miles of Matthews.',
      meta:'188 N Trade St · Downtown Matthews · Sat 8am–12pm (Apr–Nov) · matthewsfarmersmarket.com',
      img:'https://static.wixstatic.com/media/17ea1a_38c82503dce946a4b901267d84a2d78e~mv2.jpg' },

    { lat:35.1218, lon:-80.7202, n:18, cat:'arts',
      name:'Renfrow Hardware',
      short:'120-year-old institution · seeds · hardware · historic',
      desc:'A 120-year-old downtown institution on the National Register of Historic Places, selling hardware, seeds, and general goods just as it has since 1900.',
      meta:'188 N Trade St · Downtown Matthews · Tue–Fri 8am–4pm · renfrowhardware.com',
      img:'https://www.renfrowhardware.com/wp-content/uploads/2017/06/home-1122x490.jpg',
      tags:['local'] },

    { lat:35.1205, lon:-80.7200, n:19, cat:'arts',
      name:'ZABS Place',
      short:'Thrift & designer boutique · social enterprise · downtown',
      desc:'A community thrift and designer boutique that employs and empowers young adults with disabilities — shop with purpose in the heart of downtown Matthews.',
      meta:'100 N Trade St · Downtown Matthews · Mon–Thu 10am–6pm, Fri 10am–4pm, Sun 12–6pm · zabsplace.org',
      img:'https://zabsplace.org/wp-content/uploads/2019/05/logo_19.png', logoOnly:true, logoScale:'70%', bgColor:'#ffffff',
      tags:['local'] },

    /* ── FAMILY & WELLNESS ── */
    { lat:35.1182, lon:-80.7195, n:20, cat:'family',
      name:'Matthews Community Center',
      short:'Classes · theater · yoga · music · all ages',
      desc:'The town\'s civic hub offering dance, art, yoga, and music programs for all ages, plus the Fullwood Theater hosting local performances year-round.',
      meta:'100 E McDowell St · Matthews · Mon–Fri 9am–8pm, Sat 9am–2pm, Sun 1–6pm · matthewsnc.gov',
      img:'https://applications-media.feverup.com/image/upload/w_620,h_420,c_fill,q_auto,f_auto,g_auto/fever2/plan/photo/ff1e1f96-3437-11f1-9191-52d442d483c4.jpg',
      tags:['family','kids'] },

    { lat:35.1068, lon:-80.7238, n:21, cat:'family',
      name:'High Five Playhouse',
      short:'Indoor playground · ages 10 & under · birthday parties',
      desc:'A squeaky-clean indoor playground featuring ball pits, slides, swings, and a cafe — perfect for playdates and birthday parties for kids 10 and under.',
      meta:'10101 E Independence Blvd · Matthews · Mon–Thu 10am–7pm, Fri–Sun 10am–8pm · highfiveplayhouse.com',
      img:'https://highfiveplayhouse.com/wp-content/uploads/2023/09/student-hanging-from-green-bar-1-1.png',
      tags:['kids','family'] },

    { lat:35.1208, lon:-80.7195, n:22, cat:'family',
      name:'Matthews Yoga Collective',
      short:'Community yoga · downtown studio · all levels',
      desc:'A welcoming downtown yoga studio offering a community-centered practice just steps from Trade Street shops and cafes.',
      meta:'189 N Trade St · Downtown Matthews · matthewsyogacollective.com',
      img:'https://matthewsyogacollective.com/wp-content/uploads/2025/11/about-img.png',
      tags:['local'] },

    { lat:35.1145, lon:-80.7175, n:23, cat:'family',
      name:'Re·Invent Fitness',
      short:'Hot yoga · circuit training · boutique studio',
      desc:'A boutique studio blending hot yoga and circuit strength training in a supportive environment that pushes you to discover a stronger version of yourself.',
      meta:'1150 Crews Rd · Matthews · Daily 9am–6pm · reinventfitness.com',
      img:'https://images.squarespace-cdn.com/content/v1/5f7897d7ed6aec42e58fe542/1603722930171-DXKZNWZ7F9B49XRYSF4J/AF8I4905.jpg',
      tags:['local'] },

    /* ── KIDS & FAMILY ── */
    { lat:35.1058, lon:-80.7312, n:26, cat:'kids',
      name:'Matthews Sportsplex',
      short:'11 fields · tournaments · playground · all ages',
      desc:'A massive multi-sport complex with 11 lighted fields, a 4,300-seat stadium, and a playground — perfect for catching a tournament or letting the kids run wild.',
      meta:'2425 Sports Pkwy · Matthews · Daily 8am–9pm · charlottesports.com',
      img:'https://crva.imgix.net/Matthews-SportsPlex-Kyo-H-Nam-2018-36-of-60.jpg?auto=compress%2Cformat&fit=crop&fm=webp&ixlib=php-3.1.0&q=80&v=1614621202',
      tags:['kids','family','outdoor'] },

  ],

  streetLabels: [
    { lat: 35.1210, lon: -80.7200, name: 'N Trade St', rotate: 80 },
    { lat: 35.1185, lon: -80.7170, name: 'E John St', rotate: 0 },
    { lat: 35.1100, lon: -80.7190, name: 'Monroe Rd', rotate: 80 },
    { lat: 35.1175, lon: -80.7225, name: 'Weddington Rd', rotate: 0 },
  ],

  landmarks: [
    { lat: 35.1178, lon: -80.7182, name: 'Matthews Town Hall', type: 'gov' },
    { lat: 35.1145, lon: -80.7210, name: 'Matthews Elementary', type: 'school' },
    { lat: 35.1220, lon: -80.7195, name: 'Parking', type: 'parking' },
    { lat: 35.1198, lon: -80.7208, name: 'Parking', type: 'parking' },
    { lat: 35.1108, lon: -80.7118, name: '', type: 'duck' },
    { lat: 35.1038, lon: -80.7092, name: '', type: 'duck' },
  ],

  areaLabels: [
    { lat: 35.1210, lon: -80.7200, name: 'Downtown Matthews' },
    { lat: 35.1100, lon: -80.7185, name: 'Matthews Station' },
    { lat: 35.1050, lon: -80.7100, name: 'Squirrel Lake' },
    { lat: 35.1035, lon: -80.7088, name: 'Beatty Park' },
  ],

  printRails: {
    top: [
      { head: '🍽 Eat &amp; Drink', cls: 'eat', nums: [4, 5, 6, 7, 8, 24], lightText: true },
    ],
    left: [
      { head: '☕ Coffee', cls: 'coffee', nums: [9, 10, 11] },
      { head: '🧒 Kids &amp; Family', cls: 'kids', nums: [21, 15, 26] },
    ],
    right: [
      { head: '🍺 Brew &amp; Bar', cls: 'coffee', nums: [1, 2, 3] },
      { head: '🌿 Outdoors', cls: 'do', nums: [12, 13, 14] },
    ],
    mapBelow: [
      { head: '🎨 Arts &amp; Community', cls: 'fam', nums: [16, 17, 18, 19] },
    ],
    bottom: [
      { head: '🏃 Family &amp; Wellness', cls: 'fam', nums: [20, 22, 23] },
    ],
  },
};
