window.REGION = {
  id: 'rock-hill',
  name: 'Downtown Rock Hill',
  sub: '· YORK COUNTY · SOUTH CAROLINA · 2026 EDITION ·',
  credit: '© Rock Hill Map · 2026 · rockHillMap.com',
  interactiveCredit: 'Click any marker · Pan &amp; zoom to explore · rockHillMap.com',
  center: [34.9325, -81.0220],
  zoom: 15,
  printZoom: 15,

  palette: {
    '--ink':          '#3A2208',
    '--frame':        '#5A3818',
    '--parch':        '#F0E2B8',
    '--parch-dark':   '#D6BD8A',
    '--accent':       '#A02018',
    '--navy':         '#003579',
    '--green':        '#4A8228',
    '--inner-border': '#C8A878',
    '--tile-filter':  'sepia(0.35) saturate(1.4) hue-rotate(-12deg) contrast(0.92) brightness(1.1)',
    '--tile-blend':   'multiply',
    '--tile-opa':     '0.85',
  },

  /* Optional per-theme palette overrides — Rock Hill only */
  themes: {
    navy: {
      '--ink': '#1A2A4A', '--frame': '#1A2A4A', '--parch': '#FBF5E5',
      '--parch-dark': '#E8DCC0', '--accent': '#B83020', '--navy': '#1A2A4A',
      '--green': '#4A6228', '--inner-border': '#A8C0D8',
      '--tile-filter': 'sepia(0.20) saturate(0.85) hue-rotate(-5deg) contrast(0.95)',
      '--tile-blend': 'multiply', '--tile-opa': '0.82',
    },
    forest: {
      '--ink': '#2A3A1A', '--frame': '#2A3A1A', '--parch': '#ECDCB0',
      '--parch-dark': '#C8B888', '--accent': '#884818', '--navy': '#2A3A1A',
      '--green': '#4A6818', '--inner-border': '#A8B888',
      '--tile-filter': 'sepia(0.30) saturate(0.85) hue-rotate(15deg) contrast(0.95)',
      '--tile-blend': 'multiply', '--tile-opa': '0.80',
    },
    coastal: {
      '--ink': '#1E3A5A', '--frame': '#1E3A5A', '--parch': '#F4ECD4',
      '--parch-dark': '#DDD4B8', '--accent': '#C84838', '--navy': '#1E3A5A',
      '--green': '#5A8A48', '--inner-border': '#A8C0C8',
      '--tile-filter': 'hue-rotate(-15deg) saturate(0.85) brightness(1.05) contrast(0.92)',
      '--tile-blend': 'multiply', '--tile-opa': '0.78',
    },
    park: {
      '--ink': '#1A3A5A', '--frame': '#0F4A5A', '--parch': '#FFF4D8',
      '--parch-dark': '#FAE5B0', '--accent': '#E62D3D', '--navy': '#0F4A5A',
      '--green': '#2FA94F', '--inner-border': '#C8E0C0',
      '--tile-filter': 'saturate(2.2) hue-rotate(8deg) brightness(1.18) contrast(1.0)',
      '--tile-blend': 'normal', '--tile-opa': '0.95',
    },
    sunset: {
      '--ink': '#582818', '--frame': '#582818', '--parch': '#F4DCAC',
      '--parch-dark': '#E8B888', '--accent': '#C04030', '--navy': '#6A2818',
      '--green': '#806028', '--inner-border': '#C8A878',
      '--tile-filter': 'sepia(0.55) saturate(1.5) hue-rotate(-25deg) contrast(0.92) brightness(1.05)',
      '--tile-blend': 'multiply', '--tile-opa': '0.78',
    },
  },

  cats: {
    outdoor: '#3A6818',
    food:    '#A02018',
    coffee:  '#5A2A08',
    beer:    '#5A3008',
    arts:    '#380A38',
    family:  '#0A2848',
  },

  legend: [
    { color: '#3A6818', label: 'Outdoors' },
    { color: '#A02018', label: 'Eat &amp; Drink' },
    { color: '#5A2A08', label: 'Coffee' },
    { color: '#5A3008', label: 'Brewing' },
    { color: '#380A38', label: 'Arts &amp; Music' },
    { color: '#0A2848', label: 'Family Fun' },
  ],

  places: [
    /* downtown core */
    { lat:34.9252, lon:-81.0297, n:1,  cat:'coffee', name:'MudBug Coffee',
      short:'Where the map began.',
      desc:'Where the map began. Locally roasted, great pastries.',
      meta:'134 E. Main St · Mon–Sat 6–6', img:'assets/coffee_shop.png' },
    { lat:34.9248, lon:-81.0274, n:2,  cat:'arts',   name:'Old Brick Live',
      short:'Historic music venue. Local acts Thu–Sat.',
      desc:'Historic music venue. Acoustic &amp; local acts Thu–Sat.',
      meta:'212 E. Main St · oldbricklive.com' },
    { lat:34.9248, lon:-81.0252, n:3,  cat:'food',   name:'Vintage Vinyl &amp; Cafe',
      short:'Records · espresso · late tacos',
      desc:'Records, espresso, late-night tacos.',
      meta:'· Main St' },
    { lat:34.9255, lon:-81.0228, n:4,  cat:'food',   name:'Old Town Bistro',
      short:'Farm-to-table Southern with patio',
      desc:'Farm-to-table Southern with patio.',
      meta:'· Main &amp; Trade' },
    { lat:34.9255, lon:-81.0200, n:5,  cat:'arts',   name:'York Heritage Center',
      short:'Local history exhibits, free admission',
      desc:'Local history exhibits, free admission.',
      meta:'· Main St · 10–5 daily' },
    { lat:34.9248, lon:-81.0170, n:6,  cat:'food',   name:'Improper Pig',
      short:'BBQ joint with bourbon list',
      desc:'BBQ joint with bourbon list.',
      meta:'· Main St' },
    { lat:34.9248, lon:-81.0145, n:7,  cat:'food',   name:'Suntex BBQ',
      short:"Pitmaster proud since '87",
      desc:"Pitmaster proud since '87.",
      meta:'Hwy 21 · Tue–Sun 11–8' },

    /* brewing district */
    { lat:34.9290, lon:-81.0240, n:8,  cat:'beer',   name:'White Street Brewing Co.',
      short:'Craft beer · live music!',
      desc:'Craft beer, live music, Sunday brunch.',
      meta:'324 W. White St · whitestreetbrewing.com', img:'assets/brewery.png' },
    { lat:34.9295, lon:-81.0265, n:9,  cat:'beer',   name:'Pints &amp; Plates',
      short:'Craft beer with elevated pub fare',
      desc:'Craft beer with elevated pub fare.',
      meta:'· White St' },
    { lat:34.9290, lon:-81.0210, n:10, cat:'beer',   name:'Brushcreek Distillery',
      short:'Small-batch bourbon · tours',
      desc:'Small-batch bourbon, tours by appointment.',
      meta:'· White St' },

    /* coffee */
    { lat:34.9270, lon:-81.0120, n:11, cat:'coffee', name:'Catawba Grounds',
      short:'Books · coffee · good vibes',
      desc:'Books, coffee, good vibes.',
      meta:'River District · catawbagrounds.com' },
    { lat:34.9395, lon:-81.0200, n:12, cat:'coffee', name:'Hexagon Coffee',
      short:'Specialty roasts &amp; pastries',
      desc:'Specialty roasts &amp; pastries.',
      meta:'620 Oakland Ave · Daily 7–5' },

    /* civic + cultural */
    { lat:34.9222, lon:-81.0287, n:13, cat:'arts',   name:'York County Museum',
      short:'Dinos · Stars · Wonder!',
      desc:'Dinosaurs, stars, local heritage.',
      meta:'4621 Mt. Gallant Rd · chmuseums.org', img:'assets/museum.png' },
    { lat:34.9372, lon:-81.0335, n:14, cat:'arts',   name:'Winthrop University',
      short:'1886 campus · Tillman Hall',
      desc:'1886 campus, Tillman Hall, Conservatory.',
      meta:'701 Oakland Ave · winthrop.edu', img:'assets/winthrop_tower.png' },

    /* outdoors + family */
    { lat:34.9262, lon:-81.0183, n:15, cat:'outdoor', name:'Glencairn Garden',
      short:'Free admission · Festivals · Weddings',
      desc:'Free admission. Festivals &amp; weddings.',
      meta:'725 Crest St · Dawn–dusk', img:'assets/fountain.png' },
    { lat:34.9398, lon:-81.0395, n:16, cat:'outdoor', name:'Riverwalk Amphitheater',
      short:'Outdoor concerts on the Catawba',
      desc:'Outdoor concerts on the Catawba.',
      meta:'· Riverwalk Rd', img:'assets/amphitheater.png' },
    { lat:34.9420, lon:-81.0400, n:17, cat:'outdoor', name:'Catawba River Outfitters',
      short:'Kayak · SUP · Guided Floats',
      desc:'Kayak, SUP, guided floats.',
      meta:'Riverwalk Launch · catawbaoutfitters.com', img:'assets/kayak.png' },
    { lat:34.9460, lon:-81.0130, n:18, cat:'outdoor', name:'Manchester Meadows',
      short:'Soccer · baseball · miles of trail',
      desc:'Soccer, baseball, miles of trail.',
      meta:'· North side of town' },
    { lat:34.9295, lon:-81.0000, n:19, cat:'outdoor', name:'Cherry Park',
      short:'Premier baseball complex',
      desc:'Premier baseball complex. Tournaments year-round.',
      meta:'2461 Cherry Rd' },
    { lat:34.9210, lon:-81.0185, n:20, cat:'family',  name:'Fewell Park',
      short:'Playground · picnic · splash pad',
      desc:'Playground, picnic shelter, splash pad.',
      meta:'· South of Old Town' },
    { lat:34.9245, lon:-81.0050, n:21, cat:'family',  name:'Sky Zone Rock Hill',
      short:'Trampolines · dodgeball · foam pit',
      desc:'Trampolines, dodgeball, foam pit.',
      meta:'· Cherry Rd' },
  ],

  printRails: {
    left: [
      { head: '☕ Coffee &amp; Cafés', cls: 'coffee', nums: [1, 11, 12] },
      { head: '🥾 Get Outside!',       cls: 'do',     nums: [17, 15, 16] },
    ],
    right: [
      { head: '🍽 Eat &amp; Drink',    cls: 'eat',    nums: [7, 8, 3] },
      { head: '⭐ Families &amp; Kids', cls: 'fam',    nums: [14, 13, 21] },
    ],
  },
};
