window.REGION = {
  id: 'waxhaw',
  name: 'Waxhaw',
  sub: '· UNION COUNTY · NORTH CAROLINA · 2026 EDITION ·',
  credit: '© Waxhaw Map · 2026 · waxhawMap.com',
  interactiveCredit: 'Click any marker · Pan &amp; zoom to explore · waxhawMap.com',
  center: [34.9244, -80.7434],
  zoom: 16,
  printZoom: 16,

  palette: {
    '--ink':          '#2B1A0E',
    '--frame':        '#5C3A1E',
    '--parch':        '#F7F0E6',
    '--parch-dark':   '#E0D0B8',
    '--accent':       '#A0522D',
    '--navy':         '#5C3A1E',
    '--green':        '#4A7C3F',
    '--inner-border': '#C4A882',
    '--tile-filter':  'saturate(1.1) brightness(1.05) contrast(0.93)',
    '--tile-blend':   'normal',
    '--tile-opa':     '1',
  },

  cats: {
    outdoor: '#4A7C3F',
    food:    '#A0522D',
    coffee:  '#6B3A2A',
    arts:    '#7B5E3A',
    family:  '#2E6B5E',
  },

  legend: [
    { color: '#4A7C3F', label: 'Outdoors' },
    { color: '#A0522D', label: 'Eat &amp; Drink' },
    { color: '#6B3A2A', label: 'Coffee' },
    { color: '#7B5E3A', label: 'Arts &amp; Antiques' },
    { color: '#2E6B5E', label: 'Family Fun' },
  ],

  places: [
    /* Downtown core */
    { lat:34.9244, lon:-80.7434, n:1, cat:'arts',
      name:'Historic Downtown Waxhaw',
      short:'Antiques · boutiques · local charm',
      desc:'Waxhaw\'s beloved walkable downtown — lined with antique shops, boutiques, art galleries, and local eateries.',
      meta:'W. South Main St · Mon–Sat 10am–6pm',
      img:'https://visitwaxhaw.com/wp-content/uploads/2021/03/downtown-waxhaw.jpg' },
    { lat:34.9238, lon:-80.7440, n:2, cat:'arts',
      name:'Waxhaw Antique District',
      short:'Dozens of dealers · vintage finds',
      desc:'One of the best antique districts in the Carolinas — dozens of dealers packed into charming storefronts.',
      meta:'S. Main St · Tue–Sun 10am–5pm',
      img:'https://visitwaxhaw.com/wp-content/uploads/2021/03/antiques.jpg' },
    { lat:34.9250, lon:-80.7428, n:3, cat:'coffee',
      name:'Mugs Coffee Bar',
      short:'Local café · espresso · pastries',
      desc:'Cozy downtown café serving expertly pulled espresso, seasonal lattes, and fresh-baked pastries.',
      meta:'W. South Main St · Mon–Sat 7am–5pm, Sun 8am–3pm',
      img:'https://images.squarespace-cdn.com/content/v1/mugs-coffee.jpg' },
    { lat:34.9242, lon:-80.7445, n:4, cat:'food',
      name:'110 Bistro',
      short:'Farm-to-table · craft cocktails',
      desc:'Upscale yet relaxed farm-to-table bistro with a seasonal menu, craft cocktails, and a beautiful patio.',
      meta:'110 N. Church St · Tue–Sat 5–10pm',
      img:'https://images.squarespace-cdn.com/content/v1/110-bistro.jpg' },
    { lat:34.9247, lon:-80.7437, n:5, cat:'food',
      name:'South Main Kitchen',
      short:'Southern comfort · brunch · dinner',
      desc:'Beloved neighborhood spot serving elevated Southern comfort food — famous for weekend brunch.',
      meta:'S. Main St · Wed–Sun 9am–9pm',
      img:'https://images.southmainkitchen.com/hero.jpg' },
    { lat:34.9240, lon:-80.7430, n:6, cat:'food',
      name:'Waxhaw Station Brewing',
      short:'Craft beer · food trucks · patio',
      desc:'Local craft brewery with rotating taps, regular food truck events, and a lively outdoor patio.',
      meta:'E. South Main St · Thu–Fri 4–10pm, Sat–Sun 12–10pm',
      img:'https://waxhawbrewing.com/wp-content/uploads/brewery-patio.jpg' },

    /* Arts & Culture */
    { lat:34.9255, lon:-80.7442, n:7, cat:'arts',
      name:'Museum of the Waxhaws',
      short:'Local history · Andrew Jackson heritage',
      desc:'Explore the rich history of the Waxhaw region — including its connection to President Andrew Jackson.',
      meta:'8215 Waxhaw Hwy · Tue–Sat 10am–4pm · Free admission',
      img:'https://museumofthewaxhaws.org/wp-content/uploads/museum.jpg' },
    { lat:34.9248, lon:-80.7450, n:8, cat:'arts',
      name:'Waxhaw Town Hall Arts',
      short:'Local art shows · community events',
      desc:'Community arts hub hosting rotating local art exhibitions, concerts, and seasonal town events.',
      meta:'W. South Main St · Mon–Fri 9am–5pm',
      img:'https://visitwaxhaw.com/wp-content/uploads/arts-center.jpg' },
    { lat:34.9235, lon:-80.7425, n:9, cat:'arts',
      name:'Waxhaw Yoga Studio',
      short:'Yoga · pilates · meditation',
      desc:'Peaceful yoga and pilates studio in the heart of downtown, offering classes for all skill levels.',
      meta:'S. Main St · Mon–Sat 6am–8pm, Sun 8am–1pm',
      img:'https://images.yoga-studio.com/waxhaw.jpg' },

    /* Outdoors */
    { lat:34.9380, lon:-80.7520, n:10, cat:'outdoor',
      name:'Cane Creek Park',
      short:'Trails · lake · camping · sports',
      desc:'Union County\'s premier park — paved trails, a fishing lake, campgrounds, sports fields, and a splash pad.',
      meta:'5213 Harkey Rd · Daily 7am–dusk · unioncountyparks.org',
      img:'https://www.unioncountyparks.org/wp-content/uploads/cane-creek-park.jpg' },
    { lat:34.9300, lon:-80.7460, n:11, cat:'outdoor',
      name:'Waxhaw Greenway Trail',
      short:'Paved trail · bikes · strollers',
      desc:'Scenic paved greenway trail winding through Waxhaw — perfect for morning runs, bike rides, and strollers.',
      meta:'Access off W. South Main St · Dawn–dusk · Free',
      img:'https://visitwaxhaw.com/wp-content/uploads/greenway.jpg' },
    { lat:34.9180, lon:-80.7380, n:12, cat:'outdoor',
      name:'McMullen Creek Greenway',
      short:'Natural trails · bird watching',
      desc:'Peaceful natural trail following McMullen Creek — great for bird watching, nature walks, and quiet reflection.',
      meta:'Waxhaw area · Dawn–dusk · Free',
      img:'https://visitwaxhaw.com/wp-content/uploads/creek-trail.jpg' },

    /* Coffee & Cafés */
    { lat:34.9252, lon:-80.7432, n:13, cat:'coffee',
      name:'The Village Grind',
      short:'Specialty coffee · cozy nooks',
      desc:'Charming specialty coffee shop tucked in a historic storefront — excellent pour-overs and local artwork on the walls.',
      meta:'Downtown Waxhaw · Mon–Fri 7am–5pm, Sat 8am–4pm',
      img:'https://images.thevillagegrind.com/shop.jpg' },
    { lat:34.9260, lon:-80.7445, n:14, cat:'coffee',
      name:'Starbucks Waxhaw',
      short:'Drive-thru · Reserve drinks',
      desc:'Conveniently located Starbucks with drive-thru, Nitro Cold Brew, and Oleato drinks.',
      meta:'Providence Rd S · Daily 5:30am–9pm',
      img:'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/starbucks.jpg' },

    /* More Food */
    { lat:34.9236, lon:-80.7438, n:15, cat:'food',
      name:'Bad Daddy\'s Burger Bar',
      short:'Gourmet burgers · craft beer',
      desc:'Award-winning gourmet burger bar with creative toppings, crispy fries, and a great local beer selection.',
      meta:'Providence Rd S · Mon–Thu 11am–10pm, Fri–Sat 11am–11pm',
      img:'https://baddaddysburgerbar.com/wp-content/uploads/burgers.jpg' },
    { lat:34.9228, lon:-80.7442, n:16, cat:'food',
      name:'Firebirds Wood Fired Grill',
      short:'Wood-fired steaks · happy hour',
      desc:'Upscale casual dining with handcrafted wood-fired dishes, an extensive cocktail menu, and a great happy hour.',
      meta:'Providence Rd S · Daily 11am–10pm',
      img:'https://firebirdsrestaurants.com/wp-content/uploads/wood-fired.jpg' },
    { lat:34.9245, lon:-80.7455, n:17, cat:'food',
      name:'El Camino Mexican Grill',
      short:'Authentic Mexican · margaritas',
      desc:'Family-owned Mexican restaurant with authentic recipes, fresh guacamole, and the best margaritas in Waxhaw.',
      meta:'W. South Main St · Mon–Sun 11am–10pm',
      img:'https://images.elcaminowaxhaw.com/interior.jpg' },
    { lat:34.9253, lon:-80.7420, n:18, cat:'food',
      name:'Waxhaw Ice House',
      short:'Live music · BBQ · cold drinks',
      desc:'Waxhaw\'s favorite outdoor hangout — BBQ, cold drinks, live music on weekends, and a laid-back vibe.',
      meta:'E. North Main St · Wed–Sun 11am–late',
      img:'https://waxhawicehouse.com/wp-content/uploads/icehouse.jpg' },

    /* Family */
    { lat:34.9265, lon:-80.7430, n:19, cat:'family',
      name:'Waxhaw Athletic Park',
      short:'Sports fields · playground',
      desc:'Well-maintained athletic park with multi-use sports fields, a playground, and walking paths.',
      meta:'Waxhaw · Daily 7am–dusk · Free',
      img:'https://visitwaxhaw.com/wp-content/uploads/athletic-park.jpg' },
    { lat:34.9232, lon:-80.7448, n:20, cat:'family',
      name:'Cane Creek Splash Pad',
      short:'Free water play · kids · summer',
      desc:'Free interactive splash pad at Cane Creek Park — a summertime favorite for families with young kids.',
      meta:'Cane Creek Park · Memorial Day–Labor Day · Free',
      img:'https://www.unioncountyparks.org/wp-content/uploads/splash-pad.jpg' },
    { lat:34.9258, lon:-80.7438, n:21, cat:'family',
      name:'Waxhaw Farmers Market',
      short:'Local produce · crafts · community',
      desc:'Weekly farmers market with fresh local produce, handmade crafts, baked goods, and live music.',
      meta:'Downtown Waxhaw · Sat 8am–noon (seasonal)',
      img:'https://visitwaxhaw.com/wp-content/uploads/farmers-market.jpg' },
    { lat:34.9240, lon:-80.7460, n:22, cat:'family',
      name:'Waxhaw Community Center',
      short:'Classes · events · recreation',
      desc:'Full-service community center with fitness classes, youth programs, and seasonal community events.',
      meta:'Waxhaw · Mon–Fri 6am–9pm, Sat 8am–5pm',
      img:'https://visitwaxhaw.com/wp-content/uploads/community-center.jpg' },

    /* Arts cont. */
    { lat:34.9243, lon:-80.7435, n:23, cat:'arts',
      name:'Waxhaw Art Galleries',
      short:'Local artists · rotating exhibits',
      desc:'A cluster of independent art galleries showcasing works by local and regional artists in all mediums.',
      meta:'S. Main St · Tue–Sat 10am–5pm',
      img:'https://visitwaxhaw.com/wp-content/uploads/art-gallery.jpg' },
    { lat:34.9250, lon:-80.7443, n:24, cat:'arts',
      name:'Carolina Thread Trail',
      short:'Regional greenway · nature · views',
      desc:'Part of the 1,500-mile regional greenway network — scenic wooded paths connecting communities.',
      meta:'Waxhaw trailhead off Providence Rd · Dawn–dusk',
      img:'https://carolinathreadtrail.org/wp-content/uploads/trail.jpg' },
  ],

  printRails: {
    top: [
      { head: '🎨 Arts &amp; Antiques', cls: 'fam', nums: [1, 2, 7, 8, 23, 24] },
    ],
    left: [
      { head: '☕ Coffee &amp; Cafés', cls: 'coffee', nums: [3, 13, 14] },
      { head: '🥾 Get Outside!',       cls: 'do',     nums: [10] },
    ],
    right: [
      { head: '🍽 Eat &amp; Drink', cls: 'eat', nums: [4, 5, 6, 15, 16] },
    ],
    mapBelow: [
      { head: '🌿 Wellness &amp; Community', cls: 'fam', nums: [9, 22] },
    ],
    bottom: [
      { head: '🎳 Family &amp; Fun', cls: 'fam', nums: [19, 20, 21] },
    ],
  },
};
